env:
  - PROTOBUF_VERSION=2.5.0 PATH=/home/travis/bin:$PATH
language: scala
scala:
  - 2.10.5
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
sudo: false
before_install:
  - ./install-protobuf.sh
script:
  - sbt -jvm-opts travis/jvmopts.compile compile
  - sbt -jvm-opts travis/jvmopts.test coverage test
  - sbt -jvm-opts travis/jvmopts.test scalastyle
after_success:
  - bash <(curl -s https://codecov.io/bash)
